### ISSUE TITLE
Cannot create new server

### ISSUE THREAD

**Issue by Deester4x4jr** [signalfire/serverpilot#2]
Hello,

First off, thanks for writing this wrapper.  I'm sure a lot of time and energy went into it.

I have successfully listed all of the servers in my account, however adding a server is not going so smoothly.  I have tried it many different ways, and I get the following error:

```
ServerPilot: 400 Bad Request (RestClient::BadRequest)
/var/lib/gems/2.3.0/gems/rest-client-2.0.0/lib/restclient/abstract_response.rb:223:in `exception_with_response`
/var/lib/gems/2.3.0/gems/rest-client-2.0.0/lib/restclient/abstract_response.rb:103:in `return!'
/var/lib/gems/2.3.0/gems/rest-client-2.0.0/lib/restclient/request.rb:860:in `process_result'
/var/lib/gems/2.3.0/gems/rest-client-2.0.0/lib/restclient/request.rb:776:in `block in transmit'
/usr/lib/ruby/2.3.0/net/http.rb:853:in `start'
/var/lib/gems/2.3.0/gems/rest-client-2.0.0/lib/restclient/request.rb:766:in `transmit'
/var/lib/gems/2.3.0/gems/rest-client-2.0.0/lib/restclient/request.rb:215:in `execute'
/var/lib/gems/2.3.0/gems/ServerPilot-0.0.4/lib/ServerPilot.rb:99:in `execute_api_command'
/var/lib/gems/2.3.0/gems/ServerPilot-0.0.4/lib/ServerPilot.rb:109:in `execute_request'
/var/lib/gems/2.3.0/gems/ServerPilot-0.0.4/lib/ServerPilot.rb:121:in `method_missing'
```

For reference, this is the command I am trying:

`new_server = sp.post_servers 'test-connect-server'`

I tried to run it as you have in the docs:

`new_server = sp.post_servers {name: 'test-connect-server'}`

but that results in a much less exciting error:

```
shared/serverpilot/serverpilot-provision-script.rb:26: syntax error, unexpected ':', expecting '}'
  new_server = sp.post_servers {name: 'test-connect-server'}
                                     ^
```

Any chance you might know what's going on?

Thanks!

-Josh-

**Comment by signalfire** [comment]
Hi Josh

Thanks for the feedback. I created this quite a while ago and as such I don't have a test environment up and running at the minute. However I will take a proper look at the errors and come back to you by the weekend.

Rob

**Comment by Deester4x4jr** [comment]
Sounds good, thank you for the help.

-Josh-

**Comment by Deester4x4jr** [comment]
I am new to Ruby, so please forgive what is probably painfully obvious for most.  I was sending the request incorrectly.  Here is the proper syntax:

`new_server = sp.post_servers({name: 'server-name'})`

Thanks for offering to help!  Also, thanks for writing such easy to follow code.  I actually just learned a whole lot by reading through all of it.

-Josh-
